<template>
  <form>
    <div >
      All Posts
    </div>
    <div >
      Most Readed
    </div>
    <div >
      Most Liked
    </div>
  <div class="search" >
    <p v-show="!oui" @click="toggleSearch">
      <ion-icon name="search-outline"></ion-icon>
    </p>
    <div v-show="oui" class="search-container">
      <div><ion-icon name="search-outline"></ion-icon></div>
      <input type="text" placeholder="Search" />
      <div @click="toggleSearch"><ion-icon name="close-outline"></ion-icon></div>
    </div>
  </div>
  <div class="login">
    Log in / Sign up
  </div>
  </form>
  <section class="unified-container">
  <article class="content">
    <div class="info">
    <p class="profile"><img :src="profile" alt="profile"/></p>
    <p class="info1"><span class="name">{{ article.username }} </span>.{{ article.currentdate }} . {{article.timeread}} read 
    <span id="dots" @click="share"><ion-icon name="ellipsis-vertical"></ion-icon></span>
    </p>
    </div>
    <div class="share" v-show="shar">
      <ion-icon name="arrow-redo-outline"></ion-icon>
      <input type="submit" value="Share Post">
    </div>
     <h1 class="title">  {{article.title}}    </h1>
    <p class="detail">{{article.details}}</p>
    <div class="album">
      <img :src="article1" alt="photo1">
            <img :src="article2" alt="photo1">
                  <img :src="profile" alt="photo1">

    </div>
    <div class="footer">
      <hr>
      <div class="interaction">
    <p>{{article.views}} views</p> <p>{{article.comment}} comments</p><p>{{article.likes}} <ion-icon @click="like()" v-show="!liked" name="heart-outline"></ion-icon><ion-icon @click="like()" v-show ="liked" name="heart"></ion-icon></p> 
      </div>
    </div>
  </article>
  </section>
</template>

<script>
import article1 from '@/assets/article1.webp';
import profile from '@/assets/profile1.jpg';
import article2 from '@/assets/article2.jpg';
export default {
  data() {
    return {
      article: null,
      article1,
      profile,
      article2,
      oui:false,
      isHovered:false,
      shar:false,
      liked:false
    };
  },
  created() {
    const articleId = this.$route.params.id; // Récupère l'ID de l'article depuis l'URL

    const currentdate = new Date().toLocaleDateString(); // Définit une date actuelle

    const articles = [
      {
        id: 1,
        details: 'Here are more details about the first blog post...',
        username: "khalid kidarine",
        currentdate,
        timeread: "1 min ",
        title: 'Exploring the Multilayered Surface Finishing of Futuristic "Obsidian" RocksExploring the Multilayered Surface Finishing of Futuristic "Obsidian" Rocks',
        details: 'Take an upake an up-close look at the surface finishing of the futuristic "Obsidian," achieved through multiple layers of paint with varying affinities. Each "Obsidian" rock is unique with its "fingerprints," reflecting light in its own way depending on the viewing angle.Original design story:In mineralogy, obsidian is a naturally occurring volcanic glass formed as an extrusive igneous rock."The Obsidian" by TerraLiving is where Zen meets technology & minimalism, adopting the dark, mystic grey of the obsidian surface.A classic Zen-inspired minimalist artwork, "the Obsidian" is an oasis of peace sculpted out of geometric rocks generated by computational design, carpeted by lush greens.An artwork of contemplation, "the Obsidian" is intended to be meditative and functional in design. -close look at the surface finishing of the futuristic "Obsidian," achieved through multiple layers of paint with varying...Take an up-close look at the surface finishing of the futuristic "Obsidian," achieved through multiple layers of paint with varying...',
        views: 200,
        comment: 20,
        likes: 34
      },
      {
        id: 2,
        article: 'article2',
        username: "user two",
        profile: 'profile2',
        currentdate: currentdate,
        timeread: "2 min",
        title: 'Another fascinating article title',
        details: 'This is the introduction to another fascinating article..Here are more details about the second blog post....',
        views: 200,
        comment: 10,
        likes: 30
      },
      {
        id: 3,
        article: 'article3',
        username: "user three",
        profile: 'profile3',
        currentdate: currentdate,
        timeread: "3 min",
        title: 'The Wonders of Modern Architecture',
        details: 'An insight into the modern architectural marvels...Here are more details about the third blog post...',
        views: 300,
        comment: 15,
        likes: 40
      },
      {
        id: 4,
        article: 'article4',
        username: "user four",
        profile: 'profile4',
        currentdate: currentdate,
        timeread: "4 min",
        title: 'Understanding Quantum Computing',
        details: 'A deep dive into the complexities of quantum computing...Here are more details about the fourth blog post...',
        views: 400,
        comment: 25,
        likes: 50
      },
      {
        id: 5,
        article: 'article5',
        username: "user five",
        profile: 'profile5',
        currentdate: currentdate,
        timeread: "5 min",
        title: 'Advancements in Artificial Intelligence',
        details: 'Exploring the recent advancements in AI technology...Here are more details about the fifth blog post...',
        views: 500,
        comment: 30,
        likes: 60
      },
      {
        id: 6,
        article: 'article6',
        username: "user six",
        profile: 'profile6',
        currentdate: currentdate,
        timeread: "6 min",
        title: 'The Future of Space Exploration',
        details: 'Looking ahead to the future of space travel and exploration...Here are more details about the sixth blog post...',
        views: 600,
        comment: 35,
        likes: 70
      }
    ];

    this.article = articles.find(article => article.id == articleId);
  },
  
   methods: {
    toggleSearch() {
      this.oui = !this.oui;
    },
    share(){
       this.shar= !this.shar;
    },
    like(){
      if(this.liked){
        this.likes --;
      }else{
        this.likes ++;
      }
    this.liked = !this.liked;
    }
  }
};
</script>
<style scoped>

form {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
  align-items: center;
  width: 80%; 
  height: 60px;
  padding: 5px;
  margin-left: 10%; 
  transition: cursor 0.3s;
  cursor: default;
  margin-top: 5%;
}

form > div:hover,.name:hover,#dots:hover,
.title:hover,.share:hover{
  cursor: pointer;
  color: rgb(23, 179, 153)
}
.login{
  color: rgb(78, 78, 204);
  border: 1px solid rgb(78, 78, 204);
  padding: 5%;
}
.search-container{
    display: flex;
    flex-direction: row;
}
input[type=text]{
    outline: none;
    border: none;
    border-bottom: 1px solid gray;
    width: 60%;
}

.unified-container {
  border: 1px solid gray;
  display: flex;
  width: 70%;
  margin-left: 15%;
  padding: 3%;
  margin-bottom: 35px;
  margin-top:3% ;
  padding-bottom:5% ;
}
.unified-container >img{
  cursor: pointer;
}
.profile{
  border: 5px solid #fff;
  border-radius:50% ;
  overflow: hidden;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 50px;
  width: 50px;
  cursor: pointer;
  background-color: black;
}
.profile img{
  object-fit: cover;
  width: 100%;
  height: 100%;
}
.content{
  width: 100%;
  padding-left: 25px;
  padding-top: 10px;
  position: relative;
}
.info{
  display: flex;
  flex-direction: row;
  width: 97%;
  height: 50px;
  margin-bottom: 5%;}
  .info1{
  display: grid;
  grid-template-columns: 1fr 6fr auto;
  word-spacing: 3px;
  margin-top: 4%;
  margin-left: 2%;
  width: 100%;
  height: 40px;
}
.share{
  width: 25%;
  height: 40px;
  margin-left:570px ;
  border: 2px solid white;
  box-shadow: 2px 2px 10px black;
  border-radius:2% ;
  position: absolute;
  z-index: 10;
  background-color: white;
}
.share input{
  font-size: 18px;
  background-color: #fff;
  border: none;
  margin-right: 7px;
  cursor: pointer;
  }
.share ion-icon{
  font-size: 30px;
  margin-bottom: -5px;
  margin-left: 2px;
}
.album{
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
}
.album img{
  max-width: 300px;
  max-height: 300px;
}
.footer{
  width: 90%;
  height: 100px;
  position:absolute;
  left: 20px;
  padding-bottom: 5px;
}
.interaction {
  display: grid;
  grid-template-columns: 1fr 5fr auto; 
  align-items: center; 
  font-size: 18px;
}
.interaction p:nth-child(2):hover{
  color: rgb(23, 179, 153);
  cursor: pointer;
}
.interaction p:nth-child(3) {
  justify-self: end; 
  justify-content: center;
  align-items: center;
}
.interaction p:nth-child(3) >ion-icon {
  color: red;
  cursor: pointer;
}
</style>